"""initial_schema

Revision ID: 7822084ddf4c
Revises: 
Create Date: 2026-02-15 21:50:16.139195
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision: str = '7822084ddf4c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('background_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.String(), nullable=False),
    sa.Column('task_key', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('background_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_background_tasks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_tasks_task_key'), ['task_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_tasks_task_type'), ['task_type'], unique=False)

    with op.batch_alter_table('training_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('perplexity', sa.Float(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    with op.batch_alter_table('training_runs', schema=None) as batch_op:
        batch_op.drop_column('perplexity')

    with op.batch_alter_table('background_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_background_tasks_task_type'))
        batch_op.drop_index(batch_op.f('ix_background_tasks_task_key'))
        batch_op.drop_index(batch_op.f('ix_background_tasks_id'))

    op.drop_table('background_tasks')
    # ### end Alembic commands ###
